env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - airbnb
  - airbnb-typescript
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: "module"
  project: ./tsconfig.json
plugins:
  - react
  - react-hooks # add hooks
  - "@typescript-eslint"
rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/react-in-jsx-scope: off
  react/jsx-curly-brace-presence: error
  react/jsx-boolean-value: error
  # タグを閉じる
  react/self-closing-comp:
    - error
    - component: true
      html: true
  # 関数タイプの指定
  react/function-component-definition:
    - 2
    - namedComponents: arrow-function
      unnamedComponents: function-expression
