env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - airbnb
  - airbnb-typescript
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: "module"
  project: ./tsconfig.json
plugins:
  - react
  - react-hooks # add hooks
  - "@typescript-eslint"
  - import
rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/react-in-jsx-scope: off
  react/jsx-curly-brace-presence: error
  react/jsx-boolean-value: error
  # 空のタグを閉じる
  react/self-closing-comp:
    - error
    - component: true
      html: true
  # 関数タイプの指定
  react/function-component-definition:
    - 2
    - namedComponents: arrow-function
      unnamedComponents: function-expression
  # import時の拡張子不要
  import/extensions:
    - error
    - never
  react/button-has-type: off
  react/jsx-props-no-spreading: off
  jsx-a11y/label-has-associated-control: off
  react/require-default-props: off
  import/prefer-default-export: off
  import/no-default-export: error
  "@typescript-eslint/no-unused-expressions": off
overrides:
  - files:
      - "**/*.stories.*"
    rules:
      import/no-anonymous-default-export: "off"
      import/no-extraneous-dependencies: "off"
      import/no-default-export: "off"
#       import/no-default-export: "off"
#       import/prefer-default-export: "error"
